In [37]:
import numpy as np

a=np.arange(10)
print(a)
print(a[4:9])
a[0]

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]


0

In [19]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
i=0
j=0
print(a[i:i+2, j:j+2])

[[0 1]
 [4 5]]


In [32]:
a=[1,2,3,4,5]
max(a)

5

In [46]:
import collections

l = ['a', 'a', 'a', 'a', 'b', 'c', 'c']
c = collections.Counter(l)
print(type(c))
print(c)
print(c.values())


<class 'collections.Counter'>
Counter({'a': 4, 'c': 2, 'b': 1})
dict_values([4, 1, 2])
